[env:esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

; --- Upload & Monitor Einstellungen ---
monitor_speed = 115200
;monitor_filters = esp32_exception_decoder   ; <--- Übersetzt den Crash in Klartext
;build_type = debug                          ; <--- Baut zusätzliche Debug-Infos in den Code

; =========================================================
; UPLOAD OPTION 1: USB (Aktiv für den allerersten Upload)
; =========================================================
;upload_speed = 921600
; WICHTIG FÜRS TEAM: Lasst den upload_port am besten auskommentiert!
; PlatformIO findet den Port (Mac: /dev/cu... | Win: COMx) meist automatisch. 
; Nur bei Problemen hart eintragen:
; upload_port = /dev/cu.usbserial-0001  ; (Für Mac)
; upload_port = COM4                    ; (Für Windows)

; =========================================================
; UPLOAD OPTION 2: OTA (Für alle späteren Uploads über WLAN)
; =========================================================
upload_protocol = espota
upload_port = twm_variac.local 
; WICHTIG FÜR WINDOWS: Falls twm_variac.local nicht gefunden wird,
; stattdessen die direkte IP eintragen, z.B.:
; upload_port = 192.168.1.50

; --- Flash & Board Konfiguration ---
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_qspi ; Erforderlich für N16R2 (16MB Flash / 2MB PSRAM)
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L

; --- Dateisystem & Partitionierung ---
board_build.filesystem = littlefs
board_build.partitions = partitions.csv

; --- Compiler Build Flags ---
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_ARCH_ESP32=1
    -D BOARD_HAS_PSRAM=1
    
    ; --- TFT_eSPI Konfiguration ---
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_MISO=13
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=14
    -D TFT_RST=47
    -D TFT_BL=35
    -D TFT_BACKLIGHT_ON=1 ; (1 entspricht HIGH)
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_FONT6=1
    -D LOAD_FONT7=1
    -D LOAD_FONT8=1
    -D LOAD_GFXFF=1
    -D SMOOTH_FONT=1
    -D USE_LITTLEFS=1
    -D SPI_FREQUENCY=27000000
    -D SPI_READ_FREQUENCY=20000000
    -D SPI_TOUCH_FREQUENCY=2500000
    -D USE_HSPI_PORT=1

; --- Bibliotheken (Dependencies) --- 
lib_deps = 
    waspinator/AccelStepper @ ^1.64.0
    blemasle/MCP23017 @ ^2.0.0
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
    bodmer/TFT_eSPI @ ^2.5.43
    tzapu/WiFiManager @ ^2.0.17
    madhephaestus/ESP32Encoder @ ^0.11.7
    bblanchon/ArduinoJson @ ^6.21.5
    esp32async/ESPAsyncWebServer @ ^3.10.3